# Manual de instruções para o Render.com

services:
  # Serviço 1: O Banco de Dados (Nossa Caixa d'Água)
  - type: psql
    name: banco-blog-nilton
    plan: free

  # Serviço 2: O Site Laravel (Nossa Casa)
  - type: web
    name: blog-nilton-stein
    runtime: php      # <-- AQUI ESTÁ A MÁGICA! Forçamos o ambiente PHP.
    plan: free
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: psql # O Render vai substituir isso pelo endereço interno do banco
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          type: psql
          name: banco-blog-nilton
          property: database
      - key: DB_USERNAME
        fromService:
          type: psql
          name: banco-blog-nilton
          property: user
      - key: DB_PASSWORD
        fromService:
          type: psql
          name: banco-blog-nilton
          property: password
      - key: APP_URL
        fromService:
          type: web
          name: blog-nilton-stein
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY # Esta chave é um segredo, vamos adicioná-la manualmente.
        sync: false
