# Manual de instruções CORRIGIDO para o Render.com

# Seção para o banco de dados
databases:
  - name: banco-blog-nilton
    plan: free

# Seção separada para o site
services:
  - type: web
    name: blog-nilton-stein
    runtime: php
    plan: free
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: # Usamos fromDatabase para conectar
          name: banco-blog-nilton
          property: host
      - key: DB_PORT
        fromDatabase:
          name: banco-blog-nilton
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: banco-blog-nilton
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: banco-blog-nilton
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: banco-blog-nilton
          property: password
      - key: APP_URL
        fromService:
          type: web
          name: blog-nilton-stein
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY # Esta chave secreta será adicionada manualmente
        sync: false
