# Este arquivo está CORRETO. Não adicione a APP_KEY aqui.

databases:
  - name: banco-blog-nilton
    plan: free
    region: oregon

services:
  - type: web
    name: blog-nilton-stein
    plan: free
    region: oregon
    buildCommand: "composer install --no-dev --optimize-autoloader && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: banco-blog-nilton
          property: host
      - key: DB_PORT
        fromDatabase:
          name: banco-blog-nilton
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: banco-blog-nilton
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: banco-blog-nilton
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: banco-blog-nilton
          property: password
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
